name: Deploy para InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Obter cÃ³digo mais recente
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sincronizar arquivos com InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          # Use ponto barra ./ para ajudar o robÃ´ a achar a pasta certa
          server-dir: ./htdocs/
          
          # Lista de bloqueio reforÃ§ada para evitar o erro 553
          exclude: |
            **/.git*
            **/.git/**
            **/.github/**
            **/documentacao/**
            **/*.sql
            README.md
            LICENSE
            composer.lock
            composer.json
