name: Deploy para InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Obter cÃ³digo mais recente
        uses: actions/checkout@v4

      - name: ðŸ“‚ Sincronizar arquivos com InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          # Pasta de destino no servidor (pÃºblica)
          server-dir: /htdocs/
          
          # Arquivos e pastas para NÃƒO enviar
          exclude: |
            **/.git*
            **/.github*
            **/*.sql
            README.md
            **/documentacao/**